### ISSUE TITLE
Interact with notifications

### ISSUE THREAD

**Issue by silentguy256** [SteamGifts/SteamGifts#24]
If you go to your notifications, you can't reply or go to the post this is about or anything. There should at least be a go to topic, if possible combined with #22

**Comment by mabako** [comment]
This is pretty much the use-case #22 is aimed at. Viewing a full discussion is most likely not what you want to view a single notification.

**Comment by mabako** [comment]
Fixed in 172801a761c9e9b69b0a3cce721cbb77d7d2fe37, 5a8118e2e60d619005355836362d4913117f1ff5 and cf5f89ae0625acda3b16ee15a94de3273e0488a1.
