### ISSUE TITLE
No connection 

### ISSUE THREAD

**Issue by klorydryk** [SteamGifts/SteamGifts#28]
Hardware : onePlus one. 
Software : Cyanogen-os 12.1.1

This is impossible to connect to my account steam. After giving the steam code, the loading picture turn... Indefinitely.

**Comment by mabako** [comment]
Any chance you could post the logcat output?

**Comment by klorydryk** [comment]
I've tried to get a logcat with aLogCat, but don't see anything helping.
I'll retry to find something.

**Comment by KeerealYo** [comment]
`
![screenshot_2016-04-16-13-02-45](https://cloud.githubusercontent.com/assets/18491058/14580365/8b97ee0c-03ba-11e6-872a-b2436b187d57.png)
I` just installed app from F-droid and got the same problem. When I try to log in, app open Steam's window and then open SG's main page like full version of site in mobile browser (screenshot added). When I re-open app, I still not logged in.
Android 5.0.2
Also I tried all 3 browser options in app's settings

**Comment by mabako** [comment]
Hey,

Please install either 1.2.3 or 1.3-beta.8, this has been fixed recently.

KeerealYo notifications@github.com schrieb am Fr., 15. Apr. 2016, 23:18:

**Comment by KeerealYo** [comment]
Yes, it work in 1.2.4. Thank you! Seems everything great now.
P.s. it took me about 2 hours to found new versions, cause I'm very new here
