### ISSUE TITLE
GA List broken

### ISSUE THREAD

**Issue by silentguy256** [SteamGifts/SteamGifts#30]
As mentioned [in the SG thread](http://www.steamgifts.com/go/comment/mo72BMg), it seems that one of the updates to the site broke GA lists.

**Comment by supagit** [comment]
The problem is in the Utils.loadGiveaway

giveaway.setInternalGameId(Integer.parseInt(popup.attr("data-game-id")));

popup.attr("data-game-id")) returns an empty string

**Comment by silentguy256** [comment]
Nah, that can't really be the problem, can it? cause loading a giveaway works fine... 

I kinda expect the parsing in loadGiveawaysFromList to fail. But I can't really play around with it cause I have no fitting environment set up for compiling thia

**Comment by mabako** [comment]
Loading the giveaway list calls Utils.loadGiveaway iirc. I'll play around a bit with it tomorrow.
