### ISSUE TITLE
Giveaway views are broken again

### ISSUE THREAD

**Issue by anonymous-user** [SteamGifts/SteamGifts#38]
I cannot view the lists of giveaways. It just says the usual failed to fetch items. However I can access individual giveaway pages and the discussion board.

**Comment by mabako** [comment]
cg probably broke something by updating the site again.

How dare he. :expressionless:

**Comment by mabako** [comment]
Fixed in 1.5-beta.3 (e369ca8404320261e34f5bd9efbe54b98e21854c) and 1.4.2 (0f20cbb9fe41e7344f9ec5ccf2ee06f9d5abf44d).
