### ISSUE TITLE
Filter by platform

### ISSUE THREAD

**Issue by gsantner** [SteamGifts/SteamGifts#39]
Currently there is no way to filter the games by platform inside the app.
Please add this feature.

Version 1.4.2 (vanilla)

**Comment by mabako** [comment]
Is there any way to actually filter games on the normal site? All I know of is a setting, but that should apply to your account so you'd only need to change it on the desktop to apply on mobile as well.

**Comment by gsantner** [comment]
Both: Just global, no current filter

**Comment by mabako** [comment]
The global filter set on the website applies to the app as well.

Since the giveaway list has no indication whether a giveaway is for mac, linux or windows, I'm not entirely sure how I'd handle it in-app either.

Is there any user script that offers this?

**Comment by gsantner** [comment]
Ups, I corrected the response.
I didn't look at the code, do you scrape web content or use an API?

**Comment by mabako** [comment]
Steamgifts has no API, so its all web scraping.

**Comment by gsantner** [comment]
If the scraping way is prefered:
```
<div class="sysreq_tabs">
									<div class="sysreq_tab" data-os="win">
						Windows					</div>
									<div class="sysreq_tab active" data-os="mac">
						Mac OS X					</div>
									<div class="sysreq_tab" data-os="linux">
						SteamOS + Linux					</div>
								<div style="clear: left;"></div>
			</div>
```

This is some piece of HTML found on an game (`http://store.steampowered.com/app/<ID>/`). And the `<ID>` is available inside the SteamGifts-html. Note: This is `http`, not `https` and it seems like https is not available.

**Option 2:** Their API could also be used, but I don't know if there is an call available which delivers the OS information. But note, that can't be check in then anymore, because this will require an Steam API key, and I think this would also mean the app cannot be published on **F-Droid** anymore.

**Option 3:** Maybe an other Steam service has these informations.

**Comment by mabako** [comment]
I'm currently using http://store.steampowered.com/api/appdetails/?appids=420 to figure out the steam app info when you swipe to the right on a single giveaway page.

This *does* have platform info, but according to [this](https://steamdb.info/forum/296/steam-api-game-informations/) there's rate limiting and can't handle multiple app-ids at once. If this is done on the client side (e.g. "show linux games only") that you may run into that rate limit pretty soon. You essentially have to load N games.
