### ISSUE TITLE
Sidebar items offset after upgrading to Android 7.0

### ISSUE THREAD

**Issue by entsyymi** [SteamGifts/SteamGifts#40]
After upgrading to Android N from Android M, the sidebar items show up wrong until you touch them. Whenever you scroll down and back up, the images are showing up wrong again. My device is OnePlus 3.

![screenshot_20170104-011017](https://cloud.githubusercontent.com/assets/20669459/21626619/ca3f347e-d21a-11e6-86b3-0ec09cdeb07c.png)

**Comment by mabako** [comment]
This seems to be exclusive to 7.0, as it seems to be fine in 7.1, and it only seems to be an issue the first time you open the drawer.
