### ISSUE TITLE
Page fails to load when "#" character is present

### ISSUE THREAD

**Issue by Thexder0** [SteamGifts/SteamGifts#41]
Sometimes, rarely, someone posts the giveaway "Humble Indie Bundle #xx". I noticed that, whenever that happens, the App fails to load the page with the said giveaway ("Failed to Fetch Items").

By the way, thanks for the great app! 🗡 

Cheers!

**Comment by mabako** [comment]
Do you have a link to any example?

**Comment by Thexder0** [comment]
Hm, sort of -- right now, there is a Humble Indie Bundle giveaway ending on January 7th, and the corresponding page (I mean, the giveaway list under "All") fails to load for me. More specifically: if I search for "humble" from inside the app, I also get the message "Failed to Fetch Items"! It is something about that evil giveaway, so I bet 7 internet cents that "#" is the culprit. :) :)

More possibly useful info, in case it is just me:
-- I have a Nexus 10 Tablet, running Android 5.1.1.
-- My sg for Steamgifts version: 1.5-beta3 (strawberry).

Cheers!

**Comment by Thexder0** [comment]
Ah, so it was *not* the character #... I owe you 7 internet cents, it seems!

Cheers!
