### ISSUE TITLE
Filter dialog not properly displayed on some devices

### ISSUE THREAD

**Issue by mabako** [SteamGifts/SteamGifts#45]
People with the following devices have mentioned an issue whereas only the first row of the giveaway filter dialog is shown:

- LG V20
- Nexus 6p on Android 7.1.1

![unnamed](https://cloud.githubusercontent.com/assets/125113/21907028/109ef3ce-d90e-11e6-862e-8a6b006ba08d.png)

**Comment by silentguy256** [comment]
I have this problem if my LG G3 is in landscape mode (or switches to it while filter dialog is open) if that is of any help

**Comment by loic-martinez-freelance** [comment]
I can confirm the problem if I switch to landscape mode 

On Honor 8

**Comment by loic-martinez-freelance** [comment]
Look like it's corrected on the latest beta

**Comment by mabako** [comment]
Probably fixed in 1.5.2.
