### ISSUE TITLE
The buttons for entering giveaways don't update when your number of points changes

### ISSUE THREAD

**Issue by The-Fireplace** [SteamGifts/SteamGifts#53]
So, when you enter giveaways, your points go down. However, when your points drop below the amount required for a giveaway, the button doesn't become greyed out. To make them update, you currently have to scroll to get them off the screen, then scroll back to them.

**Comment by chickdan** [comment]
Are you entering giveaways on another device to create this behavior?

**Comment by The-Fireplace** [comment]
No

**Comment by The-Fireplace** [comment]
Here, I made a video demonstrating the bug. As you can see, when I enter the giveaway and my points drop, the buttons for the other giveaways, which I no longer have points to enter, don't become greyed out.
https://youtu.be/zo-Q8BKGHlI

**Comment by chickdan** [comment]
Thanks for the video! It really helped narrow things down!

**Comment by mabako** [comment]
Thanks to the help of @chickdan, this should be resolved in the next update.
