### ISSUE TITLE
Avatars not loading while in discussion overview

### ISSUE THREAD

**Issue by einfachGaer** [SteamGifts/SteamGifts#57]
Basically I view the "All Discussions" button on the side menu to get to the thread overview page. Every OP avatar is the default "?" Steam avatar.  But in the comments section avatars are loaded properly. I'm on version 1.5.9, Android 7.1.1.
![8a8ce35e-3b30-4e47-944f-ff06f02451d0](https://user-images.githubusercontent.com/33266360/32247266-1428bfac-be82-11e7-9a6d-2f67b2ebfe23.jpg)

**Comment by mabako** [comment]
Thanks for your report, will be fixed in 1.5.10.
