### ISSUE TITLE
Unable to log-in

### ISSUE THREAD

**Issue by Kasrii** [SteamGifts/SteamGifts#60]
Whenever attempting to login, it would get stuck on a continuous loading screen

**Comment by mabako** [comment]
I'm not entirely sure why that would be; I've tried just now and it seems to work fine. Can you log in on your mobile browser (not the sg app)?

**Comment by Kasrii** [comment]
After logging in and registering on the steamgifts website, the app now perfectly works, thank you for clearing up such a simple process
