### ISSUE TITLE
filter WISHLIST ?

### ISSUE THREAD

**Issue by usuarionuevor** [SteamGifts/SteamGifts#65]
Is it possible to add a filter to only show games on your WISHLIST?

**Comment by chickdan** [comment]
@usuarionuevor if you are logged in, then when you open the menu you can hit `Wishlist` in the Giveaways section. 

![screenshot_1526610868](https://user-images.githubusercontent.com/8951682/40213360-a53ce9a8-5a1a-11e8-9e39-1833ad408f6b.png)

**Comment by mabako** [comment]
Since this is already possible, I'll close this issue.

**Comment by usuarionuevor** [comment]
at least can remember wishlist tab so no need to select everytime?
